apiVersion: v1
kind: Namespace
metadata:
  name: sorrentomarina
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sorrentomarina
  namespace: sorrentomarina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorrentomarina
  template:
    metadata:
      labels:
        app: sorrentomarina
    spec:
      containers:
      - name: sorrentomarina
        image: europe-west1-docker.pkg.dev/sorrentomarina-edu/sorrentomarina/sorrentomarina:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_TYPE
          value: sqlite
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: sorrentomarina
  namespace: sorrentomarina
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sorrentomarina